--
-- create table shows
-- (
--     id        integer      not null,
--     date      integer      not null,
--     hour      integer      not null,
--     show_name varchar(255) not null,
--     primary key (id)
-- );
--
-- alter table shows
--     drop constraint if exists uk_k2bdj4abvw50iw4voriswlj0x ;
--
-- alter table shows
--     drop constraint if exists uk_k2bdj4abvw50iw4voriswlj0x ;
